/*
 * Copyright (C) 2022 Intel Corporation
 * SPDX-License-Identifier: BSD-3-Clause
 */
package models

const (
	ReportReserved1Bytes     = 28
	ReportReserved2Bytes     = 32
	ReportReserved3Bytes     = 96
	ReportReserved4Bytes     = 60
	EnclaveReportLength      = 384
	AttributeSize            = 16
	UserDataSize             = 20
	ReportDataSize           = 64
	QeVendorIdSize           = 16
	CPUsvnSize               = 16
	HashSize                 = 32
	Ecdsa256BitSignatureSize = 64
	Ecdsa256BitPubkeySize    = 64
)

// Ecdsa Quote Header
type QuoteHeader struct {
	Version            uint16               /* (0) Version of Quote data structure */
	AttestationKeyType uint16               /* (2) Type of Attestation Key used by QE */
	TeeType            uint16               /* (4) TEE which generated the quote */
	Reserved           uint16               /* (6) Reserved */
	QeSvn              uint16               /* (8) Security Version Number of QE */
	PceSvn             uint16               /* (10) Security Version Nuumber of PCE */
	QeVendorId         [QeVendorIdSize]byte /* (12) Unique Identifier of QE Vendo  */
	UserData           [UserDataSize]byte   /* (28) Custom user-defined data */
}

// Enclave Report Body
type ReportBody struct {
	CPUSvn        [CPUsvnSize]byte           /* (0) Security Version of the CPU */
	MiscSelect    uint32                     /* (16) Which fields defined in SSA.MISC */
	Reserved1     [ReportReserved1Bytes]byte /* (20) */
	SgxAttributes [AttributeSize]byte        /* (48) Any special Capabilities the Enclave possess */
	MrEnclave     [HashSize]byte             /* (64) The value of the enclave's ENCLAVE measurement */
	Reserved2     [ReportReserved2Bytes]byte /* (96) */
	MrSigner      [HashSize]byte             /* (128) The value of the enclave's SIGNER measurement */
	Reserved3     [ReportReserved3Bytes]byte /* (160) */
	SgxIsvProdID  uint16                     /* (256) Product ID of the Enclave */
	SgxIsvSvn     uint16                     /* (258) Security Version of the Enclave */
	Reserved4     [ReportReserved4Bytes]byte /* (260) */
	ReportData    [ReportDataSize]byte       /* (320) Data provided by the user */
}

// QE Authentication Data
type QEAuthData struct {
	ParsedDataSize uint16
	Data           []byte
}

// QE Certification Data
type QECertData struct {
	Type           uint16
	ParsedDataSize uint32
	Data           []byte
}

type QuoteAuthData struct {
	// ECDSA signature over Header & Enclave Report calculated using ECDSA Attestation Key.
	EnclaveReportSignature [Ecdsa256BitSignatureSize]byte
	// Public part of ECDSA Attestation Key generated by Quoting Enclave
	AttestationPublicKey [Ecdsa256BitPubkeySize]byte
	// Report of the Quoting Enclave that generated the ECDSA Attestation Key
	QeReport ReportBody
	// ECDSA signature over QE Report calculated using Provisioning Certification Key
	QeReportSignature [Ecdsa256BitSignatureSize]byte
	// Variable-length data chosen by Quoting Enclave & signed by the Provisioning Certification Key
	QeAuthData QEAuthData
	// Data required to verify the QE Report Signature.
	QeCertData QECertData
}
