/*
 * Copyright (C) 2020 Intel Corporation
 * SPDX-License-Identifier: BSD-3-Clause
 */
package parser

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/json"
	"intel/isecl/sqvs/v5/config"
	"intel/isecl/sqvs/v5/resource/domain/mocks"
	"intel/isecl/sqvs/v5/test/utils"
	"net/http"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
)

var tcbInfoJson = []byte(`{
	"tcbInfo": {
		"version": 2,
		"issueDate": "2020-06-15T06:42:01Z",
		"nextUpdate": "2020-07-15T06:42:01Z",
		"fmspc": "20606a000000",
		"pceId": "0000",
		"tcbType": 0,
		"tcbEvaluationDataNumber": 5,
		"tcbLevels": [
			{
				"tcb": {
					"sgxtcbcomp01svn": 2,
					"sgxtcbcomp02svn": 2,
					"sgxtcbcomp03svn": 0,
					"sgxtcbcomp04svn": 0,
					"sgxtcbcomp05svn": 0,
					"sgxtcbcomp06svn": 0,
					"sgxtcbcomp07svn": 0,
					"sgxtcbcomp08svn": 0,
					"sgxtcbcomp09svn": 0,
					"sgxtcbcomp10svn": 0,
					"sgxtcbcomp11svn": 0,
					"sgxtcbcomp12svn": 0,
					"sgxtcbcomp13svn": 0,
					"sgxtcbcomp14svn": 0,
					"sgxtcbcomp15svn": 0,
					"sgxtcbcomp16svn": 0,
					"pcesvn": 10
				},
				"tcbDate": "2020-05-28T00:00:00Z",
				"tcbStatus": "UpToDate"
			},
			{
				"tcb": {
					"sgxtcbcomp01svn": 1,
					"sgxtcbcomp02svn": 1,
					"sgxtcbcomp03svn": 0,
					"sgxtcbcomp04svn": 0,
					"sgxtcbcomp05svn": 0,
					"sgxtcbcomp06svn": 0,
					"sgxtcbcomp07svn": 0,
					"sgxtcbcomp08svn": 0,
					"sgxtcbcomp09svn": 0,
					"sgxtcbcomp10svn": 0,
					"sgxtcbcomp11svn": 0,
					"sgxtcbcomp12svn": 0,
					"sgxtcbcomp13svn": 0,
					"sgxtcbcomp14svn": 0,
					"sgxtcbcomp15svn": 0,
					"sgxtcbcomp16svn": 0,
					"pcesvn": 9
				},
				"tcbDate": "2020-03-22T00:00:00Z",
				"tcbStatus": "OutOfDate"
			},
			{
				"tcb": {
					"sgxtcbcomp01svn": 1,
					"sgxtcbcomp02svn": 1,
					"sgxtcbcomp03svn": 0,
					"sgxtcbcomp04svn": 0,
					"sgxtcbcomp05svn": 0,
					"sgxtcbcomp06svn": 0,
					"sgxtcbcomp07svn": 0,
					"sgxtcbcomp08svn": 0,
					"sgxtcbcomp09svn": 0,
					"sgxtcbcomp10svn": 0,
					"sgxtcbcomp11svn": 0,
					"sgxtcbcomp12svn": 0,
					"sgxtcbcomp13svn": 0,
					"sgxtcbcomp14svn": 0,
					"sgxtcbcomp15svn": 0,
					"sgxtcbcomp16svn": 0,
					"pcesvn": 0
				},
				"tcbDate": "2020-03-22T00:00:00Z",
				"tcbStatus": "OutOfDate"
			}
		]
	},
	"signature": "40b3536ee9c7028df7f0a976eaa405bc82768a258512be95fd151731f756f20a35c4a2642b91ba8083dca067932af75f1f92265dbdbd12573b05a959f6e3a677"
}`)

func TestTcbInfoStruct_GetTcbInfoInterCaList(t *testing.T) {

	var tcsInfodata TcbInfoJSON

	json.Unmarshal(tcbInfoJson, &tcsInfodata)

	tcbInfoStruct := &TcbInfoStruct{
		TcbInfoData: tcsInfodata,
	}

	tcbInfoInterCaList := tcbInfoStruct.GetTcbInfoInterCaList()
	assert.NotNil(t, tcbInfoInterCaList)

	tcbInfoRootCaList := tcbInfoStruct.GetTcbInfoRootCaList()
	assert.NotNil(t, tcbInfoRootCaList)

	tcbInfoIssueDate := tcbInfoStruct.GetTcbInfoIssueDate()
	assert.NotNil(t, tcbInfoIssueDate)

	tcbInfoNextUpdate := tcbInfoStruct.GetTcbInfoNextUpdate()
	assert.NotNil(t, tcbInfoNextUpdate)

	tcbInfoFmspc := tcbInfoStruct.GetTcbInfoFmspc()
	assert.NotNil(t, tcbInfoFmspc)

	status := tcbInfoStruct.GetTcbUptoDateStatus([]byte("testdetails1234567890"))
	assert.NotNil(t, status)
	// TCBLevels need to updated
	tcbInfoStruct.DumpTcbInfo()
}

func TestNewTcbInfo(t *testing.T) {
	scsClient := mocks.NewClientMock(http.StatusOK)
	testConfig := config.Load(testConfigFilePath)

	_, err := NewTcbInfo("testfmspctestValue", testConfig, scsClient)
	assert.Nil(t, err)

	_, err = NewTcbInfo("testfmspc", testConfig, scsClient)
	assert.NotNil(t, err)
}

func TestCompareTcbComponents(t *testing.T) {

	pckComponents := []byte("testvalue")
	pckpcesvn := uint16(12)
	tcbComponents := []byte("testvalue")
	tcbpcesvn := uint16(2)
	got := compareTcbComponents(pckComponents, pckpcesvn, tcbComponents, tcbpcesvn)
	assert.NotNil(t, got)

	pckComponents = []byte("testvalue1234567")
	tcbComponents = []byte("testvalue0123456")
	got = compareTcbComponents(pckComponents, pckpcesvn, tcbComponents, tcbpcesvn)
	assert.NotNil(t, got)

	pckpcesvn = uint16(1)
	tcbpcesvn = uint16(2)
	got = compareTcbComponents(pckComponents, pckpcesvn, tcbComponents, tcbpcesvn)
	assert.NotNil(t, got)
}

func TestGetTcbCompList(t *testing.T) {

	tcbLevelList := &TcbType{
		SgxTcbComp01Svn: 0,
		SgxTcbComp02Svn: 0,
		SgxTcbComp03Svn: 0,
		SgxTcbComp04Svn: 0,
		SgxTcbComp05Svn: 0,
		SgxTcbComp06Svn: 0,
		SgxTcbComp07Svn: 0,
		SgxTcbComp08Svn: 0,
		SgxTcbComp09Svn: 0,
		SgxTcbComp10Svn: 0,
		SgxTcbComp11Svn: 0,
		SgxTcbComp12Svn: 0,
		SgxTcbComp13Svn: 0,
		SgxTcbComp14Svn: 0,
		SgxTcbComp15Svn: 0,
		SgxTcbComp16Svn: 0,
		PceSvn:          0,
	}
	got := getTcbCompList(tcbLevelList)
	assert.NotNil(t, got)
}

func TestTcbInfoStruct_getTcbInfoStruct(t *testing.T) {

	scsClient := mocks.NewClientMock(http.StatusOK)
	testConfig := config.Load(testConfigFilePath)

	keypair, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		log.Errorf("Failed to create keypair")
	}

	utils.CreateTestCertificate(trustedSGXRootCA, "Intel SGX Root CA", keypair, true, nil)
	utils.CreateTestCertificate(intermediateSGXRootCA, "Intel SGX PCK Processor CA", keypair, true, nil)
	defer func() {
		os.Remove(trustedSGXRootCA)
		os.Remove(intermediateSGXRootCA)
	}()
	rootCert := ReadCertFromFile(t, trustedSGXRootCA)
	intermediateCert := ReadCertFromFile(t, intermediateSGXRootCA)

	rootCAMap := make(map[string]*x509.Certificate)
	interCAMap := make(map[string]*x509.Certificate)

	rootCAMap["root-ca"] = rootCert
	interCAMap["inter-ca"] = intermediateCert

	QuoteBlob := "AwACAAAAAAAFAAoAk5pyM/ecTKmUCg2zlX8GB1ePHvTyaJq7KWtZvEB5i5QAAAAAAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAADnAAAAAAAAAK1GdJ7UHrqiMnJSBB7nRtN5Gp8kMYMP7giD95k8rzFqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACD1xnnferKFHD2uvYqTXdDA8iZ22kCD5xw7h38CMfOngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU850rHdoyZhtjHHze/xDF6e/hNwogmoRd40iZZB/v+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1BAAAGp1IMlI7P+lVMltAJ3xTyeLmrqsZgK/0WBajiIPqCrhxAagIIu0l+QPoAuYmEmHm4oBrgjHhUspUmzqguHHofFM5sfwb/QU4hRFUhtwVAno0GAfyGz8nHVy64xAtRNnv7Vvk/GjislKD73UamghpdNaH5pz0/u5JhOp37YoDNVfAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAAAAAAADnAAAAAAAAAGDYWvKL6NHECgjZiwCdX4rME4Sjhc9GCADkeHkdGpecAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMT1d115ZQPpYTf3fGioKaAFasje1wFAsIGwlEkMV7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNWDh6dvJehw5sQSZBtNlOVBGafQaMeOQkvnxUAIAuYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhguSX/JsCRh+Rjbg+dTLhT3/rzHPoMboaUH2fSWNyk7h+hUPh2QloKd8slEi8ZPnXYzzhcYXqTUXwlGHkr3nkiAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8FAGwOAAAtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRTlEQ0NCSnFnQXdJQkFnSVVkK3p1Yi94WlhaSVZtd0d6MXFDUzBVcG9sNlF3Q2dZSUtvWkl6ajBFQXdJd2NERWlNQ0FHQTFVRQpBd3daU1c1MFpXd2dVMGRZSUZCRFN5QlFiR0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSU1c1MFpXd2dRMjl5Y0c5eVlYUnBiMjR4CkZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFTE1Ba0dBMVVFQmhNQ1ZWTXdIaGNOTWpFd016QTUKTURZek5USTJXaGNOTWpnd016QTVNRFl6TlRJMldqQndNU0l3SUFZRFZRUUREQmxKYm5SbGJDQlRSMWdnVUVOTElFTmxjblJwWm1sagpZWFJsTVJvd0dBWURWUVFLREJGSmJuUmxiQ0JEYjNKd2IzSmhkR2x2YmpFVU1CSUdBMVVFQnd3TFUyRnVkR0VnUTJ4aGNtRXhDekFKCkJnTlZCQWdNQWtOQk1Rc3dDUVlEVlFRR0V3SlZVekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTXhuYWJ0c0VxRlUKblNvVE50Y0kraG1xQlA3eXcvR2FldlllS3UzTVNsc21ZQVloc0RuNWNTczRObFNabkJWQ1F4NU9XaWpHNTUrZUd3QTJzWHRCZ2VhagpnZ01RTUlJREREQWZCZ05WSFNNRUdEQVdnQlJaSTlPblNxaGpWQzQ1Y0szZ0R3Y3JWeVFxdHpCdkJnTlZIUjhFYURCbU1HU2dZcUJnCmhsNW9kSFJ3Y3pvdkwzTmllQzVoY0drdWRISjFjM1JsWkhObGNuWnBZMlZ6TG1sdWRHVnNMbU52YlM5elozZ3ZZMlZ5ZEdsbWFXTmgKZEdsdmJpOTJNeTl3WTJ0amNtdy9ZMkU5Y0d4aGRHWnZjbTBtWlc1amIyUnBibWM5WkdWeU1CMEdBMVVkRGdRV0JCU2lMS2JLVHFNSgpvSHd2K01iRjQ2NmNsUGNQWXpBT0JnTlZIUThCQWY4RUJBTUNCc0F3REFZRFZSMFRBUUgvQkFJd0FEQ0NBamtHQ1NxR1NJYjRUUUVOCkFRU0NBaW93Z2dJbU1CNEdDaXFHU0liNFRRRU5BUUVFRUNDdm84ait5MGZBb2pFZVRMeExiZGd3Z2dGakJnb3Foa2lHK0UwQkRRRUMKTUlJQlV6QVFCZ3NxaGtpRytFMEJEUUVDQVFJQkFqQVFCZ3NxaGtpRytFMEJEUUVDQWdJQkFqQVFCZ3NxaGtpRytFMEJEUUVDQXdJQgpBREFRQmdzcWhraUcrRTBCRFFFQ0JBSUJBREFRQmdzcWhraUcrRTBCRFFFQ0JRSUJBREFRQmdzcWhraUcrRTBCRFFFQ0JnSUJBREFRCkJnc3Foa2lHK0UwQkRRRUNCd0lCQURBUUJnc3Foa2lHK0UwQkRRRUNDQUlCQURBUUJnc3Foa2lHK0UwQkRRRUNDUUlCQURBUUJnc3EKaGtpRytFMEJEUUVDQ2dJQkFEQVFCZ3NxaGtpRytFMEJEUUVDQ3dJQkFEQVFCZ3NxaGtpRytFMEJEUUVDREFJQkFEQVFCZ3NxaGtpRworRTBCRFFFQ0RRSUJBREFRQmdzcWhraUcrRTBCRFFFQ0RnSUJBREFRQmdzcWhraUcrRTBCRFFFQ0R3SUJBREFRQmdzcWhraUcrRTBCCkRRRUNFQUlCQURBUUJnc3Foa2lHK0UwQkRRRUNFUUlCQ2pBZkJnc3Foa2lHK0UwQkRRRUNFZ1FRQWdJQUFBQUFBQUFBQUFBQUFBQUEKQURBUUJnb3Foa2lHK0UwQkRRRURCQUlBQURBVUJnb3Foa2lHK0UwQkRRRUVCQVlRWUdvQUFBQXdEd1lLS29aSWh2aE5BUTBCQlFvQgpBVEFlQmdvcWhraUcrRTBCRFFFR0JCQWFnNUxzb1dnaS9QRFJNT3JwNVhzaE1FUUdDaXFHU0liNFRRRU5BUWN3TmpBUUJnc3Foa2lHCitFMEJEUUVIQVFFQi96QVFCZ3NxaGtpRytFMEJEUUVIQWdFQkFEQVFCZ3NxaGtpRytFMEJEUUVIQXdFQi96QUtCZ2dxaGtqT1BRUUQKQWdOSUFEQkZBaUVBcTVzK2hhWHlaRisxVE5CUVVhRExNaTBlN204V2JOTGhRNm54MHphY3NvUUNJQS9aRjIxVk9EMTdCdHcwcHBHTwp3REF5VC9LOEJiMTZ3SjhDTU1FWVljcUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDbWpDQ0FrQ2dBd0lCQWdJVVdTUFRwMHFvWTFRdU9YQ3Q0QThISzFja0tyY3dDZ1lJS29aSXpqMEVBd0l3CmFERWFNQmdHQTFVRUF3d1JTVzUwWld3Z1UwZFlJRkp2YjNRZ1EwRXhHakFZQmdOVkJBb01FVWx1ZEdWc0lFTnYKY25CdmNtRjBhVzl1TVJRd0VnWURWUVFIREF0VFlXNTBZU0JEYkdGeVlURUxNQWtHQTFVRUNBd0NRMEV4Q3pBSgpCZ05WQkFZVEFsVlRNQjRYRFRFNU1UQXpNVEV5TXpNME4xb1hEVE0wTVRBek1URXlNek0wTjFvd2NERWlNQ0FHCkExVUVBd3daU1c1MFpXd2dVMGRZSUZCRFN5QlFiR0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSU1c1MFpXd2cKUTI5eWNHOXlZWFJwYjI0eEZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFTApNQWtHQTFVRUJoTUNWVk13V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVF3cCtMYytUVUJ0ZzFICitVOEpJc01zYmpIakNrVHRYYjhqUE02cjJkaHU5eklibGhEWjdJTmZxdDNJeDhYY0ZLRDhrME5FWHJrWjY2cUoKWGExS3pMSUtvNEcvTUlHOE1COEdBMVVkSXdRWU1CYUFGT25vUkZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUZZRwpBMVVkSHdSUE1FMHdTNkJKb0VlR1JXaDBkSEJ6T2k4dmMySjRMV05sY25ScFptbGpZWFJsY3k1MGNuVnpkR1ZrCmMyVnlkbWxqWlhNdWFXNTBaV3d1WTI5dEwwbHVkR1ZzVTBkWVVtOXZkRU5CTG1SbGNqQWRCZ05WSFE0RUZnUVUKV1NQVHAwcW9ZMVF1T1hDdDRBOEhLMWNrS3Jjd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSQpNQVlCQWY4Q0FRQXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSjFxK0ZUeitnVXVWZkJRdUNnSnNGckwyVFRTCmUxYUJaNTNPNTJUakZpZTZBaUFyaVBhUmFoVVg5T2E5a0dMbEFjaFdYS1Q2ajRSV1NSNTBCcWhyTjNVVDRBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ2xEQ0NBam1nQXdJQkFnSVZBT25vUkZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUFvR0NDcUdTTTQ5QkFNQwpNR2d4R2pBWUJnTlZCQU1NRVVsdWRHVnNJRk5IV0NCU2IyOTBJRU5CTVJvd0dBWURWUVFLREJGSmJuUmxiQ0JECmIzSndiM0poZEdsdmJqRVVNQklHQTFVRUJ3d0xVMkZ1ZEdFZ1EyeGhjbUV4Q3pBSkJnTlZCQWdNQWtOQk1Rc3cKQ1FZRFZRUUdFd0pWVXpBZUZ3MHhPVEV3TXpFd09UUTVNakZhRncwME9URXlNekV5TXpVNU5UbGFNR2d4R2pBWQpCZ05WQkFNTUVVbHVkR1ZzSUZOSFdDQlNiMjkwSUVOQk1Sb3dHQVlEVlFRS0RCRkpiblJsYkNCRGIzSndiM0poCmRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUXN3Q1FZRFZRUUcKRXdKVlV6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFLzZELzFXSE5yV3dQbU5NSXlCS01XNQpKNkp6TXNqbzZ4UDJ2a0sxY2RaR2IxUEdSUC9DLzhFQ2dpRGtta2xtendMekxpKzAwMG03TExydEtKQTNvQzJqCmdiOHdnYnd3SHdZRFZSMGpCQmd3Rm9BVTZlaEVVbE0yWEVzWW1oSDhReGdzcGR3Z2dFZ3dWZ1lEVlIwZkJFOHcKVFRCTG9FbWdSNFpGYUhSMGNITTZMeTl6WW5ndFkyVnlkR2xtYVdOaGRHVnpMblJ5ZFhOMFpXUnpaWEoyYVdObApjeTVwYm5SbGJDNWpiMjB2U1c1MFpXeFRSMWhTYjI5MFEwRXVaR1Z5TUIwR0ExVWREZ1FXQkJUcDZFUlNVelpjClN4aWFFZnhER0N5bDNDQ0FTREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUIKQVRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXp3OXpkVWlVSFBNVWQwQzRteDQxamxGWmtyTTN5NWYxbGduVgpPN0Ziak9vQ0lRQ29HdFVtVDRjWHQ3Vit5U0hiSjhIb2I5QWFucHZYTkgxRVIrL2daRitvcFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

	var tcsInfodata TcbInfoJSON

	json.Unmarshal(tcbInfoJson, &tcsInfodata)

	e := &TcbInfoStruct{
		TcbInfoData:    tcsInfodata,
		RootCA:         rootCAMap,
		IntermediateCA: interCAMap,
		RawBlob:        []byte(QuoteBlob),
		Conf:           testConfig,
		Client:         scsClient,
	}
	err = e.getTcbInfoStruct("20606a000000")
	assert.Nil(t, err)

	scsClient = mocks.NewClientMock(400)
	e.Client = scsClient
	err = e.getTcbInfoStruct("20606a000000")
	assert.NotNil(t, err)

	scsClient = mocks.NewClientMock(401)
	e.Client = scsClient
	err = e.getTcbInfoStruct("20606a000000")
	assert.NotNil(t, err)

	scsClient = mocks.NewClientMock(204)
	e.Client = scsClient
	err = e.getTcbInfoStruct("20606a000000")
	assert.Nil(t, err)

	scsClient = mocks.NewClientMock(202)
	e.Client = scsClient
	err = e.getTcbInfoStruct("20606a000000")
	assert.NotNil(t, err)
}

func TestTcbInfoStruct_GetTcbInfoRootCaList(t *testing.T) {

	scsClient := mocks.NewClientMock(http.StatusOK)
	testConfig := config.Load(testConfigFilePath)

	keypair, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		log.Errorf("Failed to create keypair")
	}

	utils.CreateTestCertificate(trustedSGXRootCA, "Intel SGX Root CA", keypair, true, nil)
	utils.CreateTestCertificate(intermediateSGXRootCA, "Intel SGX PCK Processor CA", keypair, true, nil)
	defer func() {
		os.Remove(trustedSGXRootCA)
		os.Remove(intermediateSGXRootCA)
	}()
	rootCert := ReadCertFromFile(t, trustedSGXRootCA)
	intermediateCert := ReadCertFromFile(t, intermediateSGXRootCA)

	rootCAMap := make(map[string]*x509.Certificate)
	interCAMap := make(map[string]*x509.Certificate)

	rootCAMap["root-ca"] = rootCert
	interCAMap["inter-ca"] = intermediateCert

	QuoteBlob := "AwACAAAAAAAFAAoAk5pyM/ecTKmUCg2zlX8GB1ePHvTyaJq7KWtZvEB5i5QAAAAAAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAADnAAAAAAAAAK1GdJ7UHrqiMnJSBB7nRtN5Gp8kMYMP7giD95k8rzFqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACD1xnnferKFHD2uvYqTXdDA8iZ22kCD5xw7h38CMfOngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAU850rHdoyZhtjHHze/xDF6e/hNwogmoRd40iZZB/v+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1BAAAGp1IMlI7P+lVMltAJ3xTyeLmrqsZgK/0WBajiIPqCrhxAagIIu0l+QPoAuYmEmHm4oBrgjHhUspUmzqguHHofFM5sfwb/QU4hRFUhtwVAno0GAfyGz8nHVy64xAtRNnv7Vvk/GjislKD73UamghpdNaH5pz0/u5JhOp37YoDNVfAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAAAAAAADnAAAAAAAAAGDYWvKL6NHECgjZiwCdX4rME4Sjhc9GCADkeHkdGpecAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMT1d115ZQPpYTf3fGioKaAFasje1wFAsIGwlEkMV7/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNWDh6dvJehw5sQSZBtNlOVBGafQaMeOQkvnxUAIAuYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhguSX/JsCRh+Rjbg+dTLhT3/rzHPoMboaUH2fSWNyk7h+hUPh2QloKd8slEi8ZPnXYzzhcYXqTUXwlGHkr3nkiAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8FAGwOAAAtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRTlEQ0NCSnFnQXdJQkFnSVVkK3p1Yi94WlhaSVZtd0d6MXFDUzBVcG9sNlF3Q2dZSUtvWkl6ajBFQXdJd2NERWlNQ0FHQTFVRQpBd3daU1c1MFpXd2dVMGRZSUZCRFN5QlFiR0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSU1c1MFpXd2dRMjl5Y0c5eVlYUnBiMjR4CkZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFTE1Ba0dBMVVFQmhNQ1ZWTXdIaGNOTWpFd016QTUKTURZek5USTJXaGNOTWpnd016QTVNRFl6TlRJMldqQndNU0l3SUFZRFZRUUREQmxKYm5SbGJDQlRSMWdnVUVOTElFTmxjblJwWm1sagpZWFJsTVJvd0dBWURWUVFLREJGSmJuUmxiQ0JEYjNKd2IzSmhkR2x2YmpFVU1CSUdBMVVFQnd3TFUyRnVkR0VnUTJ4aGNtRXhDekFKCkJnTlZCQWdNQWtOQk1Rc3dDUVlEVlFRR0V3SlZVekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTXhuYWJ0c0VxRlUKblNvVE50Y0kraG1xQlA3eXcvR2FldlllS3UzTVNsc21ZQVloc0RuNWNTczRObFNabkJWQ1F4NU9XaWpHNTUrZUd3QTJzWHRCZ2VhagpnZ01RTUlJREREQWZCZ05WSFNNRUdEQVdnQlJaSTlPblNxaGpWQzQ1Y0szZ0R3Y3JWeVFxdHpCdkJnTlZIUjhFYURCbU1HU2dZcUJnCmhsNW9kSFJ3Y3pvdkwzTmllQzVoY0drdWRISjFjM1JsWkhObGNuWnBZMlZ6TG1sdWRHVnNMbU52YlM5elozZ3ZZMlZ5ZEdsbWFXTmgKZEdsdmJpOTJNeTl3WTJ0amNtdy9ZMkU5Y0d4aGRHWnZjbTBtWlc1amIyUnBibWM5WkdWeU1CMEdBMVVkRGdRV0JCU2lMS2JLVHFNSgpvSHd2K01iRjQ2NmNsUGNQWXpBT0JnTlZIUThCQWY4RUJBTUNCc0F3REFZRFZSMFRBUUgvQkFJd0FEQ0NBamtHQ1NxR1NJYjRUUUVOCkFRU0NBaW93Z2dJbU1CNEdDaXFHU0liNFRRRU5BUUVFRUNDdm84ait5MGZBb2pFZVRMeExiZGd3Z2dGakJnb3Foa2lHK0UwQkRRRUMKTUlJQlV6QVFCZ3NxaGtpRytFMEJEUUVDQVFJQkFqQVFCZ3NxaGtpRytFMEJEUUVDQWdJQkFqQVFCZ3NxaGtpRytFMEJEUUVDQXdJQgpBREFRQmdzcWhraUcrRTBCRFFFQ0JBSUJBREFRQmdzcWhraUcrRTBCRFFFQ0JRSUJBREFRQmdzcWhraUcrRTBCRFFFQ0JnSUJBREFRCkJnc3Foa2lHK0UwQkRRRUNCd0lCQURBUUJnc3Foa2lHK0UwQkRRRUNDQUlCQURBUUJnc3Foa2lHK0UwQkRRRUNDUUlCQURBUUJnc3EKaGtpRytFMEJEUUVDQ2dJQkFEQVFCZ3NxaGtpRytFMEJEUUVDQ3dJQkFEQVFCZ3NxaGtpRytFMEJEUUVDREFJQkFEQVFCZ3NxaGtpRworRTBCRFFFQ0RRSUJBREFRQmdzcWhraUcrRTBCRFFFQ0RnSUJBREFRQmdzcWhraUcrRTBCRFFFQ0R3SUJBREFRQmdzcWhraUcrRTBCCkRRRUNFQUlCQURBUUJnc3Foa2lHK0UwQkRRRUNFUUlCQ2pBZkJnc3Foa2lHK0UwQkRRRUNFZ1FRQWdJQUFBQUFBQUFBQUFBQUFBQUEKQURBUUJnb3Foa2lHK0UwQkRRRURCQUlBQURBVUJnb3Foa2lHK0UwQkRRRUVCQVlRWUdvQUFBQXdEd1lLS29aSWh2aE5BUTBCQlFvQgpBVEFlQmdvcWhraUcrRTBCRFFFR0JCQWFnNUxzb1dnaS9QRFJNT3JwNVhzaE1FUUdDaXFHU0liNFRRRU5BUWN3TmpBUUJnc3Foa2lHCitFMEJEUUVIQVFFQi96QVFCZ3NxaGtpRytFMEJEUUVIQWdFQkFEQVFCZ3NxaGtpRytFMEJEUUVIQXdFQi96QUtCZ2dxaGtqT1BRUUQKQWdOSUFEQkZBaUVBcTVzK2hhWHlaRisxVE5CUVVhRExNaTBlN204V2JOTGhRNm54MHphY3NvUUNJQS9aRjIxVk9EMTdCdHcwcHBHTwp3REF5VC9LOEJiMTZ3SjhDTU1FWVljcUEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDbWpDQ0FrQ2dBd0lCQWdJVVdTUFRwMHFvWTFRdU9YQ3Q0QThISzFja0tyY3dDZ1lJS29aSXpqMEVBd0l3CmFERWFNQmdHQTFVRUF3d1JTVzUwWld3Z1UwZFlJRkp2YjNRZ1EwRXhHakFZQmdOVkJBb01FVWx1ZEdWc0lFTnYKY25CdmNtRjBhVzl1TVJRd0VnWURWUVFIREF0VFlXNTBZU0JEYkdGeVlURUxNQWtHQTFVRUNBd0NRMEV4Q3pBSgpCZ05WQkFZVEFsVlRNQjRYRFRFNU1UQXpNVEV5TXpNME4xb1hEVE0wTVRBek1URXlNek0wTjFvd2NERWlNQ0FHCkExVUVBd3daU1c1MFpXd2dVMGRZSUZCRFN5QlFiR0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSU1c1MFpXd2cKUTI5eWNHOXlZWFJwYjI0eEZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFTApNQWtHQTFVRUJoTUNWVk13V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVF3cCtMYytUVUJ0ZzFICitVOEpJc01zYmpIakNrVHRYYjhqUE02cjJkaHU5eklibGhEWjdJTmZxdDNJeDhYY0ZLRDhrME5FWHJrWjY2cUoKWGExS3pMSUtvNEcvTUlHOE1COEdBMVVkSXdRWU1CYUFGT25vUkZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUZZRwpBMVVkSHdSUE1FMHdTNkJKb0VlR1JXaDBkSEJ6T2k4dmMySjRMV05sY25ScFptbGpZWFJsY3k1MGNuVnpkR1ZrCmMyVnlkbWxqWlhNdWFXNTBaV3d1WTI5dEwwbHVkR1ZzVTBkWVVtOXZkRU5CTG1SbGNqQWRCZ05WSFE0RUZnUVUKV1NQVHAwcW9ZMVF1T1hDdDRBOEhLMWNrS3Jjd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSQpNQVlCQWY4Q0FRQXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSjFxK0ZUeitnVXVWZkJRdUNnSnNGckwyVFRTCmUxYUJaNTNPNTJUakZpZTZBaUFyaVBhUmFoVVg5T2E5a0dMbEFjaFdYS1Q2ajRSV1NSNTBCcWhyTjNVVDRBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ2xEQ0NBam1nQXdJQkFnSVZBT25vUkZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUFvR0NDcUdTTTQ5QkFNQwpNR2d4R2pBWUJnTlZCQU1NRVVsdWRHVnNJRk5IV0NCU2IyOTBJRU5CTVJvd0dBWURWUVFLREJGSmJuUmxiQ0JECmIzSndiM0poZEdsdmJqRVVNQklHQTFVRUJ3d0xVMkZ1ZEdFZ1EyeGhjbUV4Q3pBSkJnTlZCQWdNQWtOQk1Rc3cKQ1FZRFZRUUdFd0pWVXpBZUZ3MHhPVEV3TXpFd09UUTVNakZhRncwME9URXlNekV5TXpVNU5UbGFNR2d4R2pBWQpCZ05WQkFNTUVVbHVkR1ZzSUZOSFdDQlNiMjkwSUVOQk1Sb3dHQVlEVlFRS0RCRkpiblJsYkNCRGIzSndiM0poCmRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUXN3Q1FZRFZRUUcKRXdKVlV6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFLzZELzFXSE5yV3dQbU5NSXlCS01XNQpKNkp6TXNqbzZ4UDJ2a0sxY2RaR2IxUEdSUC9DLzhFQ2dpRGtta2xtendMekxpKzAwMG03TExydEtKQTNvQzJqCmdiOHdnYnd3SHdZRFZSMGpCQmd3Rm9BVTZlaEVVbE0yWEVzWW1oSDhReGdzcGR3Z2dFZ3dWZ1lEVlIwZkJFOHcKVFRCTG9FbWdSNFpGYUhSMGNITTZMeTl6WW5ndFkyVnlkR2xtYVdOaGRHVnpMblJ5ZFhOMFpXUnpaWEoyYVdObApjeTVwYm5SbGJDNWpiMjB2U1c1MFpXeFRSMWhTYjI5MFEwRXVaR1Z5TUIwR0ExVWREZ1FXQkJUcDZFUlNVelpjClN4aWFFZnhER0N5bDNDQ0FTREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUIKQVRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXp3OXpkVWlVSFBNVWQwQzRteDQxamxGWmtyTTN5NWYxbGduVgpPN0Ziak9vQ0lRQ29HdFVtVDRjWHQ3Vit5U0hiSjhIb2I5QWFucHZYTkgxRVIrL2daRitvcFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

	var tcsInfodata TcbInfoJSON

	json.Unmarshal(tcbInfoJson, &tcsInfodata)

	e := &TcbInfoStruct{
		TcbInfoData:    tcsInfodata,
		RootCA:         rootCAMap,
		IntermediateCA: interCAMap,
		RawBlob:        []byte(QuoteBlob),
		Conf:           testConfig,
		Client:         scsClient,
	}

	tcbInfoRootCaList := e.GetTcbInfoRootCaList()
	assert.NotNil(t, tcbInfoRootCaList)
	tcbInfoInterCaList := e.GetTcbInfoInterCaList()
	assert.NotNil(t, tcbInfoInterCaList)
}
